// src/app/api/staff-users/route.js
// This file is for Next.js App Router API routes.

// Make sure bcryptjs is installed: npm install bcryptjs
const bcrypt = require('bcryptjs');

// Supabase client initialization (ensure these are securely configured)
const { createClient } = require('@supabase/supabase-js');
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY; // THIS IS YOUR SECRET KEY

// Initialize Supabase client with the service role key for admin operations
const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey, {
  auth: { persistSession: false } // Important for server-side, non-persisted sessions
});

// POST handler for creating a new staff user
export async function POST(request) {
  try {
    // Parse the JSON body from the incoming request
    const { username, email, password, role } = await request.json();

    // Basic validation
    if (!username || !email || !password || !role) {
      return new Response(JSON.stringify({ message: 'Missing required fields (username, email, password, role)' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // 1. Create the user in Supabase Auth using the admin client.
    const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true // Automatically confirms the user's email
    });

    if (authError) {
      console.error('Supabase Auth user creation failed:', authError.message);
      return new Response(JSON.stringify({ message: `Failed to create authentication user: ${authError.message}` }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    const userId = authData.user.id; // Get the UUID generated by Supabase Auth

    // 2. Hash the password using bcrypt for storage in your custom 'staff_users' table.
    const password_hash = await bcrypt.hash(password, 10); // 10 is the number of salt rounds

    // 3. Insert the staff user details into your 'staff_users' table.
    const { data, error } = await supabaseAdmin.from('staff_users').insert({
      id: userId, // Link to the Supabase Auth user's UUID
      username,
      email,
      password_hash, // Store the bcrypt hashed password here
      role
    }).select();

    if (error) {
      console.error('Failed to insert into staff_users table:', error.message);
      // IMPORTANT: If the insertion into 'staff_users' fails, delete the Auth user
      // to prevent orphaned authentication records.
      await supabaseAdmin.auth.admin.deleteUser(userId);
      return new Response(JSON.stringify({ message: `Failed to create staff user record: ${error.message}` }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Return a success response with the created user data
    return new Response(JSON.stringify({ message: 'Staff user created successfully', user: data[0] }), {
      status: 201,
      headers: { 'Content-Type': 'application/json' },
    });

  } catch (error) {
    // Catch any unexpected errors during the process
    console.error('Unhandled error during staff user creation:', error.message);
    return new Response(JSON.stringify({ message: 'Internal server error during user creation.' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}